name: Setup for Node.js and Build Package

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Run build
        run: |
          npm run build  # Build your project

      - name: Create staging directory and copy build artifacts
        run: |
          mkdir -p staging
          cp -r dist/* staging/  # Copy build artifacts from dist/

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NodePackage
          path: staging

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish --access public
