name: Setup for Node.js and NPM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  echo_nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # This will now create the dist directory

      - name: Create staging directory and copy artifacts
        run: |
          mkdir -p staging
          cp -r dist/* staging/  # This will work after the build

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
